version: '3'

services:
  db:
    build: ./mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'deskTravel'
    ports:
      - 3306:3306
    volumes:
      - ./mysql/mysql_volume:/var/lib/mysql
  web-back:
    build: backend/.
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/code/
    stdin_open: true
    tty: true
    ports:
      - '8000:8000'
    depends_on:
      - db
  web-front:
    build: frontend/.
    volumes:
      - ./frontend/:/usr/src/app
    command: sh -c 'cd app && npm start'
    ports:
      - 3000:3000
    tty: true
